name: 'mi_proyecto_tpch'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models", "docs"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ----------------------------------------------------------------
# CONFIGURACION DE MODELOS
# ----------------------------------------------------------------
models:
  mi_proyecto_tpch:
    
    # 1. STAGING: Vistas, raw data y rename.
    staging:
      +materialized: view
      +schema: staging
      tpch:
        +tags: ["source_layer"]

    # 2. INTERMEDIATE 
    intermediate:
      +materialized: view
      +schema: intermediate

    # 3. MARTS 
    marts:
      +materialized: table
      +schema: marts
      # permiso de lectura al rol que se quiera , cada vez que dbt cree estas tablas o full refreash
      +grants:
        select: ['reporter_role']
      
      main:
        +tags: ["domain_sales"]
      finance:
        +tags: ["domain_finance"]

# ----------------------------------------------------------------
# CONFIGURACIÓN DE TESTS 
# ----------------------------------------------------------------
#  definimos el comportamiento de los tests en funcion de la carpeta donde estan
tests:
  mi_proyecto_tpch:
    
    # Tests de Staging: Si fallan, solo avisan.
    staging:
      +severity: warn
      +store_failures: true # Guarda las filas erróneas en la BBDD para auditar
      +tags: ["quality_raw"]

    # Tests de Marts: Si fallan, detienen todo 
    marts:
      +severity: error
      +tags: ["quality_business"]